### ISSUE TITLE
PCKE

### ISSUE THREAD

**Issue by freizl** [freizl/hoauth2#134]
https://www.oauth.com/oauth2-servers/pkce/

**Comment by ChrisPenner** [comment]
Hi @freizl 👋🏼 ;

We'll be implementing the Auth for https://www.unison-lang.org/ 's CLI app soon and will need PKCE for that, I'd be happy to implement and add a PR for it here if you'd be interested.

I'm curious if you have thoughts about how it would best fit into the current design, it's a bit tricky because it requires us to share state between the Authorization request and the Token Request, but unlike the state inside `OAuth2` I don't believe that codes and verifiers used in PKCE should be re-used between multiple auth flows.

I suspect we'll either need to add some new utilities, or make the breaking change to adapt existing URI-builders to accept some new `PKCEVerifier` type, or perhaps `Maybe PKCEVerifier`.

Alternatively I think something like the following could work, we could just expose them in a new PKCE module and the user would need to know to call them manually before submitting requests:

```haskell
newPKCEVerifier :: IO PKCEVerifier

addPKCEChallengeToAuthorizationUrl :: PKCEVerifier -> URI -> URI
addPKCEVerifierToTokenUrlPostBody :: PKCEVerifier -> PostBody -> PostBody
```

Would you have any thoughts or preferences on this?
Thanks!

**Comment by freizl** [comment]
Hi @ChrisPenner!

**Comment by freizl** [comment]
Another idea (Kudos to my mentor)

```
data OAuth2
data OAuth2Pkce

authorizationUrl :: IsOAuth2 a => a -> AuthorizaionData a
accessTokenUrl :: (IsOAuth2 a) => TokenRequestData a -> ExchangeToken -> (URI, Body)
```

**Comment by freizl** [comment]
Hi @ChrisPenner, 
I'm adding PKCE support at 2.6 and here is the [release candidate](https://hackage.haskell.org/package/hoauth2-2.6.0/candidate).

I wonder if you still working on and have time to take a look to see if works for you?
The `Network.OAuth2.Experiment` is where you'd start and it has slightly different way to obtain access token.

**Comment by ChrisPenner** [comment]
Thank you for adding this feature! I went ahead and implemented the PKCE flow myself outside of the library, but I'm sure future users will really appreciate this!

**Comment by freizl** [comment]
Added support from `2.6.0`
See module comment for details: https://hackage.haskell.org/package/hoauth2-2.6.0/docs/Network-OAuth2-Experiment.html

Please open new tickets for any problems.
