### ISSUE TITLE
Fetch access token and StackExchange

### ISSUE THREAD

**Issue by nakaji-dayo** [freizl/hoauth2#47]
Hello.

I tried to authenticate with [StackExchange](https://api.stackexchange.com/docs/authentication).
Then, I have encountered problem similar to #32.

It responses `url encoded access_token`.
I'm getting error `Could not decode JSONaccess_token=xxxxx&expires=86400`.
And, I can't find endpoint that returns json.

Is there any fix about this issue ?
Should I change OAuth2.hs as @katyo did, and send PR ?

**Comment by freizl** [comment]
Will take an look to see why it happened.

if you dont mind, would you shared test code that could quickly replay the error?

for https://github.com/freizl/hoauth2/issues/32, I was confused/surprised why the response is not an decode-able json and ended up by find an new endpoint work good.

**Comment by nakaji-dayo** [comment]
I replayed error with following code.

```
{-# LANGUAGE OverloadedStrings #-}

import           Network.HTTP.Client
import           Network.HTTP.Client.TLS
import           Network.OAuth.OAuth2

oauth' = OAuth2 "${client_id}" "${client_secret}" "https://stackexchange.com/oauth" "https://stackexchange.com/oauth/access_token" (Just "http://localhost:3000")

main :: IO ()
main = do
    manager <- newManager tlsManagerSettings
    res <- fetchAccessToken manager oauth' "${code}"
    print res
```

- you can get `client_id and secret` from http://stackapps.com/apps/oauth/register
- `code` from https://stackexchange.com/oauth?client_id=${client_id}&redirect_uri=localhost:3000&state=aaaa

**Comment by freizl** [comment]
I made an super simple example here: https://github.com/freizl/hoauth2/blob/master/example/StackExchange/test.hs

Let me if it makes sense to you.

-----

According to stackexchange [API doc](https://api.stackexchange.com/docs/authentication), its access token API does not respond in JSON but an string. Though it's not part of spec but seems like people usually respond in JSON. (sees other examples and also #32, facebook eventually follow such spec as well).

Therefore, you need to extract token with an extra step and `doSimplePostRequest` here to help. 
Instead of fetch access token API and convert to JSON, this function merely return response an `ByteString` so that you could do what ever you want for the response.

**Comment by freizl** [comment]
@nakaji-dayo does it work for you?

**Comment by nakaji-dayo** [comment]
Sorry for my late reply.
It works fine.
Thanks a lot!

**Comment by freizl** [comment]
Great. let me know if any other questions/problems. thanks!
